name: "poolin"
log_level: 1
log_path: "/usr/local/logs/"
ssl_port: 10003
tcp_port: 10004
pool_ssl_address: 
  - ""
pool_tcp_address: 
  - "eth.ss.poolin.me:1883"
  - "eth.ss.poolin.me:443"
share_ssl_address: 
  - "asia1.ethermine.org:5555"
  - "asia2.ethermine.org:5555"
share_tcp_address: 
  - "asia2.ethermine.org:4444"
  - "asia2.ethermine.org:14444"
  - "asia1.ethermine.org:14444"
  - "asia1.ethermine.org:4444"
share_wallet: ""
share_name: "poolin"
share_rate: 0.01
share: 2
p12_path: "/usr/local/proxy/identity.p12"
p12_pass: "mypass"
